# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TuningMode.ui'
#
# Created: Wed Dec 13 09:59:02 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui
from ros_groundstation import plot_widget

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TuningMode(object):
    def setupUi(self, TuningMode):
        TuningMode.setObjectName(_fromUtf8("TuningMode"))
        TuningMode.resize(758, 1000)
        self.centralwidget = QtGui.QWidget(TuningMode)
        self.centralwidget.setGeometry(QtCore.QRect(0, 30, 751, 1000))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 491, 821))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalSlider = QtGui.QSlider(self.tab)
        self.horizontalSlider.setGeometry(QtCore.QRect(100, 60, 261, 29))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 20, 67, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(170, 80, 111, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(60, 70, 67, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(370, 70, 67, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(370, 130, 67, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalSlider_2 = QtGui.QSlider(self.tab)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(100, 120, 271, 29))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(170, 140, 131, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(70, 130, 67, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(70, 440, 67, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalSlider_3 = QtGui.QSlider(self.tab)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(100, 430, 271, 29))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName(_fromUtf8("horizontalSlider_3"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(180, 450, 131, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(370, 380, 67, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalSlider_4 = QtGui.QSlider(self.tab)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(100, 370, 271, 29))
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName(_fromUtf8("horizontalSlider_4"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(170, 390, 141, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(30, 330, 67, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(70, 380, 67, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(370, 440, 67, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lineEdit_7 = QtGui.QLineEdit(self.tab)
        self.lineEdit_7.setGeometry(QtCore.QRect(410, 120, 61, 27))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(self.tab)
        self.lineEdit_8.setGeometry(QtCore.QRect(410, 60, 61, 27))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.lineEdit_9 = QtGui.QLineEdit(self.tab)
        self.lineEdit_9.setGeometry(QtCore.QRect(410, 370, 61, 27))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.lineEdit_10 = QtGui.QLineEdit(self.tab)
        self.lineEdit_10.setGeometry(QtCore.QRect(410, 430, 61, 27))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalSlider_6 = QtGui.QSlider(self.tab_2)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(100, 40, 261, 29))
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName(_fromUtf8("horizontalSlider_6"))
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(370, 50, 67, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(160, 130, 131, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(70, 370, 67, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(180, 390, 131, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(370, 310, 67, 17))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(70, 310, 67, 17))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(50, 10, 67, 17))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(70, 50, 67, 17))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(160, 330, 141, 17))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(370, 110, 67, 17))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(70, 110, 67, 17))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(60, 270, 67, 17))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.tab_2)
        self.label_27.setGeometry(QtCore.QRect(170, 60, 111, 17))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(370, 370, 67, 17))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(70, 630, 67, 17))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.tab_2)
        self.label_30.setGeometry(QtCore.QRect(70, 570, 67, 17))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.tab_2)
        self.label_31.setGeometry(QtCore.QRect(370, 570, 67, 17))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.tab_2)
        self.label_32.setGeometry(QtCore.QRect(160, 590, 141, 17))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_33 = QtGui.QLabel(self.tab_2)
        self.label_33.setGeometry(QtCore.QRect(370, 630, 67, 17))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.tab_2)
        self.label_34.setGeometry(QtCore.QRect(50, 530, 67, 17))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_35 = QtGui.QLabel(self.tab_2)
        self.label_35.setGeometry(QtCore.QRect(180, 650, 131, 17))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalSlider_8 = QtGui.QSlider(self.tab_2)
        self.horizontalSlider_8.setGeometry(QtCore.QRect(100, 100, 261, 29))
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setObjectName(_fromUtf8("horizontalSlider_8"))
        self.horizontalSlider_7 = QtGui.QSlider(self.tab_2)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(100, 360, 261, 29))
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName(_fromUtf8("horizontalSlider_7"))
        self.horizontalSlider_9 = QtGui.QSlider(self.tab_2)
        self.horizontalSlider_9.setGeometry(QtCore.QRect(100, 560, 261, 29))
        self.horizontalSlider_9.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_9.setObjectName(_fromUtf8("horizontalSlider_9"))
        self.horizontalSlider_10 = QtGui.QSlider(self.tab_2)
        self.horizontalSlider_10.setGeometry(QtCore.QRect(100, 620, 261, 29))
        self.horizontalSlider_10.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_10.setObjectName(_fromUtf8("horizontalSlider_10"))
        self.lineEdit = QtGui.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(410, 40, 61, 27))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(410, 100, 61, 27))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(410, 300, 61, 27))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(410, 360, 61, 27))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(410, 560, 61, 27))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(410, 620, 61, 27))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalSlider_11 = QtGui.QSlider(self.tab_2)
        self.horizontalSlider_11.setGeometry(QtCore.QRect(100, 310, 261, 29))
        self.horizontalSlider_11.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_11.setObjectName(_fromUtf8("horizontalSlider_11"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(510, 70, 97, 22))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.label_36 = QtGui.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(510, 20, 131, 41))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.checkBox_2 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(510, 100, 97, 22))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(510, 130, 97, 22))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_4 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(510, 160, 97, 22))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.checkBox_5 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(510, 190, 97, 22))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.radioButton = QtGui.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(510, 280, 117, 22))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.label_37 = QtGui.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(510, 230, 131, 41))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.radioButton_2 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(510, 310, 117, 22))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.radioButton_3 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(510, 340, 117, 22))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.radioButton_4 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(510, 370, 117, 22))
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.radioButton_5 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(510, 400, 117, 22))
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(500, 426, 251, 41))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 470, 251, 41))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.menubar = QtGui.QMenuBar(TuningMode)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 758, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.statusbar = QtGui.QStatusBar(TuningMode)
        self.statusbar.setGeometry(QtCore.QRect(0, 0, 3, 22))
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        self.toolBar = QtGui.QToolBar(TuningMode)
        self.toolBar.setGeometry(QtCore.QRect(0, 0, 4, 13))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))

        self.retranslateUi(TuningMode)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TuningMode)

    def retranslateUi(self, TuningMode):
        TuningMode.setWindowTitle(_translate("TuningMode", "Fixed wing PID tuning", None))
        self.label.setText(_translate("TuningMode", "Roll", None))
        self.label_2.setText(_translate("TuningMode", "Derivative Gain", None))
        self.label_3.setText(_translate("TuningMode", "-1.0", None))
        self.label_4.setText(_translate("TuningMode", "0.0", None))
        self.label_5.setText(_translate("TuningMode", "3.0", None))
        self.label_6.setText(_translate("TuningMode", "Proportional Gain", None))
        self.label_7.setText(_translate("TuningMode", "0.0", None))
        self.label_8.setText(_translate("TuningMode", "0.0", None))
        self.label_9.setText(_translate("TuningMode", "Integral Gain", None))
        self.label_10.setText(_translate("TuningMode", "2.0", None))
        self.label_11.setText(_translate("TuningMode", "Proportional Gain", None))
        self.label_12.setText(_translate("TuningMode", "Course", None))
        self.label_13.setText(_translate("TuningMode", "0.0", None))
        self.label_14.setText(_translate("TuningMode", "0.2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TuningMode", "Lateral", None))
        self.label_15.setText(_translate("TuningMode", "0.0", None))
        self.label_16.setText(_translate("TuningMode", "Proportional Gain", None))
        self.label_17.setText(_translate("TuningMode", "0.0", None))
        self.label_18.setText(_translate("TuningMode", "Integral Gain", None))
        self.label_19.setText(_translate("TuningMode", "0.1", None))
        self.label_20.setText(_translate("TuningMode", "0.0", None))
        self.label_21.setText(_translate("TuningMode", "Pitch", None))
        self.label_22.setText(_translate("TuningMode", "-0.4", None))
        self.label_23.setText(_translate("TuningMode", "Proportional Gain", None))
        self.label_24.setText(_translate("TuningMode", "3.0", None))
        self.label_25.setText(_translate("TuningMode", "0.0", None))
        self.label_26.setText(_translate("TuningMode", "Altitude", None))
        self.label_27.setText(_translate("TuningMode", "Derivative Gain", None))
        self.label_28.setText(_translate("TuningMode", "0.05", None))
        self.label_29.setText(_translate("TuningMode", "0.0", None))
        self.label_30.setText(_translate("TuningMode", "0.0", None))
        self.label_31.setText(_translate("TuningMode", "0.2", None))
        self.label_32.setText(_translate("TuningMode", "Proportional Gain", None))
        self.label_33.setText(_translate("TuningMode", "0.2", None))
        self.label_34.setText(_translate("TuningMode", "Airspeed", None))
        self.label_35.setText(_translate("TuningMode", "Integral Gain", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("TuningMode", "Longitudinal", None))
        self.checkBox.setText(_translate("TuningMode", "Roll", None))
        self.label_36.setText(_translate("TuningMode", "Enabled\n"
" Autopilot Loops", None))
        self.checkBox_2.setText(_translate("TuningMode", "Course", None))
        self.checkBox_3.setText(_translate("TuningMode", "Pitch", None))
        self.checkBox_4.setText(_translate("TuningMode", "Altitude", None))
        self.checkBox_5.setText(_translate("TuningMode", "Airspeed", None))
        self.radioButton.setText(_translate("TuningMode", "Roll", None))
        self.label_37.setText(_translate("TuningMode", "Current Loop", None))
        self.radioButton_2.setText(_translate("TuningMode", "Course", None))
        self.radioButton_3.setText(_translate("TuningMode", "Pitch", None))
        self.radioButton_4.setText(_translate("TuningMode", "Altitude", None))
        self.radioButton_5.setText(_translate("TuningMode", "Airspeed", None))
        self.pushButton.setText(_translate("TuningMode", "Start Tuning Mode", None))
        self.pushButton_2.setText(_translate("TuningMode", "Stop Tuning Mode and\n"
" Enable Current Loop", None))
        self.toolBar.setWindowTitle(_translate("TuningMode", "toolBar", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TuningMode = QtGui.QWidget()
    ui = Ui_TuningMode()
    ui.setupUi(TuningMode)
    TuningMode.show()
    sys.exit(app.exec_())

