#!/usr/bin/env python
import sys

from waypoint_planning.waypoint_planning import WaypointPlanner
from rqt_gui.main import Main

plugin = 'waypoint_planning.waypoint_planning.WaypointPlanner'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
